/**
 * Dynamic app icon — auto-served at /icon.png.
 *
 * Generated by Next at request time via `ImageResponse`. We render an
 * "S" wordmark on the Step ink-black background with the amber accent
 * we use elsewhere, so the home-screen icon and the brand match.
 *
 * Returns 512x512 because that's the largest size manifests reference;
 * smaller sizes are scaled down by the OS without quality loss.
 */
import { ImageResponse } from "next/og";

export const runtime = "edge";

export const size = { width: 512, height: 512 };
export const contentType = "image/png";

export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background:
            "radial-gradient(circle at 30% 25%, #1a1410 0%, #0b0b0c 60%, #0b0b0c 100%)",
          fontFamily: "system-ui",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            width: 340,
            height: 340,
            borderRadius: 96,
            background:
              "linear-gradient(135deg, #fbbf24 0%, #f59e0b 70%, #d97706 100%)",
            boxShadow: "0 24px 60px -20px rgba(245, 158, 11, 0.55)",
            color: "#0b0b0c",
            fontSize: 280,
            fontWeight: 800,
            letterSpacing: "-0.04em",
            lineHeight: 1,
          }}
        >
          S
        </div>
      </div>
    ),
    { ...size },
  );
}
