-- Manual migration — run this once on Supabase SQL editor.
--
-- Adds the `plans` table for server-saved recommendation sets. One row
-- per plan generated by a signed-in user via /beta.
--
-- Idempotent via IF NOT EXISTS guards.

------------------------------------------------------------
-- plans
------------------------------------------------------------

CREATE TABLE IF NOT EXISTS plans (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title              TEXT NOT NULL,
  recommendations    JSONB NOT NULL,
  source_session_id  UUID,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at         TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS plans_user_id_idx     ON plans (user_id);
CREATE INDEX IF NOT EXISTS plans_created_at_idx  ON plans (created_at);

-- Keep updated_at fresh on UPDATE without app-side bookkeeping.
CREATE OR REPLACE FUNCTION plans_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS plans_set_updated_at_trg ON plans;
CREATE TRIGGER plans_set_updated_at_trg
BEFORE UPDATE ON plans
FOR EACH ROW
EXECUTE FUNCTION plans_set_updated_at();
