/**
 * Signed unsubscribe tokens for check-in emails.
 *
 * A short opaque string we embed in the unsubscribe link. The user can
 * click it from any client (no session required) and we can verify it
 * was generated by us — so a stranger can't unsubscribe someone else
 * by guessing their userId.
 *
 * Format: `<base64url(userId)>.<base64url(hmac_sha256(userId, secret))>`
 *
 * Secret: we reuse AUTH_SECRET (NextAuth's JWT signing key). That key
 * already needs to be set on every deploy, never appears client-side,
 * and rotating it would invalidate sessions — which means it's a fair
 * fate-sharing for an unsubscribe link too. Worst case if someone leaks
 * tokens: they can unsubscribe paying users from check-ins (annoying,
 * not catastrophic; one-click "resubscribe" via the account page).
 */
import { createHmac, timingSafeEqual } from "node:crypto";

const SECRET = process.env.AUTH_SECRET ?? "";

function b64url(buf: Buffer | string): string {
  return Buffer.from(buf)
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/g, "");
}

function fromB64url(s: string): Buffer {
  // Restore padding so Buffer.from accepts it.
  const pad = s.length % 4 ? "=".repeat(4 - (s.length % 4)) : "";
  return Buffer.from(s.replace(/-/g, "+").replace(/_/g, "/") + pad, "base64");
}

export function signUnsubscribeToken(userId: string): string {
  if (!SECRET) {
    throw new Error("AUTH_SECRET is not set; cannot sign unsubscribe tokens.");
  }
  const sig = createHmac("sha256", SECRET).update(userId).digest();
  return `${b64url(userId)}.${b64url(sig)}`;
}

export function verifyUnsubscribeToken(token: string): string | null {
  if (!SECRET) return null;
  const parts = token.split(".");
  if (parts.length !== 2) return null;
  const [encodedId, encodedSig] = parts as [string, string];
  let userId: string;
  let providedSig: Buffer;
  try {
    userId = fromB64url(encodedId).toString("utf-8");
    providedSig = fromB64url(encodedSig);
  } catch {
    return null;
  }
  const expectedSig = createHmac("sha256", SECRET).update(userId).digest();
  if (
    providedSig.length !== expectedSig.length ||
    !timingSafeEqual(providedSig, expectedSig)
  ) {
    return null;
  }
  // Cheap sanity check: userId looks like a UUID.
  if (!/^[0-9a-f-]{36}$/.test(userId)) return null;
  return userId;
}
